name: Run PowerShell Script
on: [push]
jobs:
  run-ps-script:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Run main.ps1
        run: |
          pwsh -File ${{ github.workspace }}\main.ps1
        shell: pwsh   
